baseURL = 'https://istwitterdeadyet.info/'
languageCode = 'en-us'
title = 'Is Twitter Dead Yet?'
theme = "hello-friend-ng"

[params]
  # dateform        = "Jan 2, 2006"
  # dateformShort   = "Jan 2"
  # dateformNum     = "2006-01-02"
  # dateformNumTime = "2006-01-02 15:04"

  # Subtitle for home
  # homeSubtitle = "Is Twitter Dead Yet?"

  # Set disableReadOtherPosts to true in order to hide the links to other posts.
  disableReadOtherPosts = true

  # Enable sharing buttons, if you like
  enableSharingButtons = false

  # Metadata mostly used in document's head
  # description = "Is Twitter Dead Yet?"
  # images = [""]

  [params.logo]
    logoMark     = ">"
    logoText     = "Is Twitter Dead Yet?"
    logoHomeLink = "/"
    logoCursorDisabled = true

  [[params.social]]
    name = "email"
    url  = "mailto:nobody@example.com"

  [[params.social]]
    name = "github"
    url  = "https://github.com/"

[taxonomies]
    category = "blog"
    tag      = "tags"
    series   = "series"

# And you can even create generic menu
  [[menu.main]]
    identifier = "github"
    name       = "Want to contribute?"
    url        = "https://github.com/tmcarr/istwitterdeadyet"